name: Trolls
version: ${version}
main: me.sirsam.trolls.Trolls
description: Plugin for trolls
author: SirSam
website: programming4life.github.io
api-version: "1.20"

commands:
  jump:
    description: Launches you high in the air!
    permission: trolls.utils.god
    permission-message: You do not have permission to use this Command!
    usage: /<command> player
  fly:
    description: Allows you to toggle flight.
    permission: trolls.utils.fly
    permission-message: You do not have permission to use this Command!
    usage: /<command> player
  godmode:
    description: Makes you invulnerable.
    permission: trolls.utils.god
    permission-message: You do not have permission to use this command!
    aliases: god
    usage: /<command> player
  sudo:
    description: Allows you to send something or execute a command from another players chat.
    permission: trolls.utils.sudo
    permission-message: You do not have permission to use this Command!
    usage: /<command> player message
  troll:
    description: Allows you to get troll items.
    permission: trolls.troll
    permission-message: You do not have permission to use this Command!
    usage: /<command> [get|reload|items|head|version|help]
  vanish:
    description: Allows you to become invisible.
    permission: trolls.utils.vanish
    permission-message: You do not have permission to use this Command!
    usage: /<command> player

permissions:
  trolls.*:
    default: op
    description: Allows you to do everything in the Trolls plugin!
    children:
      trolls.troll.*:
        default: op
        description: All permissions for the /troll command.
        children:
          trolls.troll.get: true
          trolls.troll.reload: true
          trolls.troll.items: false
          trolls.troll.head: true
          trolls.troll.version: false
          trolls.troll.help: false
      trolls.utils.*:
        default: op
        description: All permissions for utility commands.
        children:
          trolls.utils.fly: true
          trolls.utils.god: true
          trolls.utils.jump: true
          trolls.utils.vanish: true
          trolls.utils.sudo: true